title: Guanyu's Homepage
page-top-title: GuanyuQi
top-section-bg-text: Be what you wanna be
home-subtitle: GuanyuQi
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
email: gyqi@hust.edu.cn